name: Deployment Run

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment to run'
        required: true
        default: 'qawolf2'
        type: choice
        options: [qawolf2]
      workflow-folder:
        description: 'Optional workflow folder to run'
        required: false
        default: ''
      test-file:
        description: 'Optional individual test file to run'
        required: false
        default: ''

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Install Playwright
        run: npx playwright install --with-deps chromium

      - name: Set Environment Variables
        run: |
          
          echo "DEFAULT_URL=${{ secrets.QAWOLF2_DEFAULT_URL }}" >> $GITHUB_ENV
          echo "DEFAULT_URL_2=${{ secrets.QAWOLF2_DEFAULT_URL_2 }}" >> $GITHUB_ENV
          echo "DEFAULT_LOGIN=${{ secrets.QAWOLF2_DEFAULT_LOGIN }}" >> $GITHUB_ENV
          echo "DEFAULT_PASSWORD=${{ secrets.QAWOLF2_DEFAULT_PASSWORD }}" >> $GITHUB_ENV
          echo "DEFAULT_PASS_JUNE_2025=${{ secrets.QAWOLF2_DEFAULT_PASS_JUNE_2025 }}" >> $GITHUB_ENV
          echo "DEFAULT_PASS_OCT_2025=${{ secrets.QAWOLF2_DEFAULT_PASS_OCT_2025 }}" >> $GITHUB_ENV
          echo "QAWA_API_KEY=${{ secrets.QAWOLF2_QAWA_API_KEY }}" >> $GITHUB_ENV
          
          fi

      - name: Run Playwright Tests
        run: |
          if [ -n "${{ github.event.inputs.test-file }}" ]; then
            npx playwright test workflows/${{ github.event.inputs.env }}/${{ github.event.inputs.test-file }}
          elif [ -n "${{ github.event.inputs.workflow-folder }}" ]; then
            npx playwright test workflows/${{ github.event.inputs.env }}/${{ github.event.inputs.workflow-folder }}
          else
            npx playwright test --project=${{ github.event.inputs.env }}
          fi

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-deployment-${{ github.event.inputs.env }}
          path: test-results/




